from django.db import models

class User(models.Model):
  email    = models.CharField(max_length=320, primary_key=True)
  password = models.CharField(max_length=12)

  def __str__(self) -> str:
    return f"{self.email}:{self.password}"



# class Billing(models.Model):
#   user = models.ForeignKey(User, on_delete=models.CASCADE)
#   firstname = ...
#   lastname = ...

#   address = ...
#   city = ...
#   country = ...
#   postcode = ...

#   phonenumber = ...
#   email = ...

  

