from django.db import models

# class User(models.Model):
#   username = models.CharField(max_length=30)
#   password = models.CharField(max_length=30)
#   email    = models.CharField(max_length=320)

# class Billing(models.Model):
#   user = models.ForeignKey(User, on_delete=models.CASCADE)
#   firstname = ...
#   lastname = ...

#   address = ...
#   city = ...
#   country = ...
#   postcode = ...

#   phonenumber = ...
#   email = ...

  

