# Generated by Django 4.2 on 2023-04-17 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.FileField(null=True, upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])])),
            ],
        ),
    ]
