# Generated by Django 4.2 on 2023-05-02 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_episode'),
        ('profile', '0004_userfavorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'title')},
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title')},
            },
        ),
    ]
