# Generated by Django 4.2 on 2023-05-02 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_userfavorite_unique_together_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
