# Generated by Django 4.2 on 2023-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_subscriptiontype_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='type',
            field=models.CharField(choices=[('mensile', 'mensile'), ('annuale', 'annuale')], max_length=7, primary_key=True, serialize=False),
        ),
    ]
