# Generated by Django 4.2 on 2023-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_alter_subscriptiontype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
