# Generated by Django 4.2 on 2023-05-19 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_delete_rentfilm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0011_alter_usersubscription_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRentFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
    ]
