# Generated by Django 4.2 on 2023-05-19 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_userrentfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrentfilm',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
