# Generated by Django 4.2 on 2023-04-17 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumbs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg'])]),
        ),
    ]
