# Generated by Django 4.2 on 2023-05-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_episode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('num_ep', 'num_season', 'serie')},
        ),
    ]
