# Generated by Django 4.2 on 2023-04-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_category_genre_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumb',
            field=models.ImageField(upload_to='thumbs'),
        ),
    ]
