# Generated by Django 4.2 on 2023-04-14 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_film_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
