# Generated by Django 4.2 on 2023-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
