# Generated by Django 4.2 on 2023-05-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumb',
            old_name='src',
            new_name='thumb_src',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='src',
            new_name='video_src',
        ),
    ]
