# Generated by Django 4.2 on 2023-04-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_film_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='video',
            new_name='videosrc',
        ),
    ]
