# Generated by Django 4.2 on 2023-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_title_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
